#version: "3.7"

networks:
  devops_training_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.236.0/24

volumes:
  portainer-data:
  # registry-data:
  jenkins-data:
  jenkins-docker-certs:
  artifactory-data:
  postgresql-vol:
  sonarqube-vol:

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 9000:9000

  # registry:
  #   image: registry:2
  #   ports:
  #   - "5000:5000"
  #   networks:
  #     devops_training_net:
  #       aliases: 
  #         - local-registry
  #   environment:
  #     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  #   volumes:
  #     - registry-data:/data

  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      devops_training_net:
        aliases: 
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    build: 
      context: ./jenkins/.
      dockerfile: Dockerfile
    user: root
    privileged: true
    restart: on-failure
    networks:
      - devops_training_net
    hostname: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - dind
      - develop-env
      - artifactory
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
     # - SONARQUBE_HOST=http://172.16.236.10:9000

  develop-env:
    image: docker:20.10.17-cli
    container_name: develop-env
    command: sh -c 'while [ 1 ]; do sleep 1; done'
    depends_on:
      - dind
    networks:
      devops_training_net:
        ipv4_address: 172.16.236.20
        aliases: 
          - develop-env
    ports:
      - 18080:8080
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - jenkins-docker-certs:/certs/client:ro

  artifactory:
    image: sonatype/nexus3
    ports:
      - "40081:8081"
    volumes:
      - artifactory-data:/nexus-data
    networks:
      devops_training_net:
        ipv4_address: 172.16.236.4
        aliases: 
          - artifactory
    hostname: artifactory
    restart: always

  sonarqube:
    image: sonarqube:9.9.0-community
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-vol:/opt/sonarqube
    ports:
      - "9009:9000"
    hostname: sonarqube
    networks:
      devops_training_net:
        ipv4_address: 172.16.236.10
        aliases: 
          - sonarqube

  sonardb:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql-vol:/var/lib/postgresql
    hostname: sonardb
    networks:
      devops_training_net:
        aliases: 
          - sonardb

  java-app-github-runner:
    build:
      context: github-runner
      args:
        RUNNER_VERSION: '2.323.0'
    depends_on:
      - dind
    networks:
      - devops_training_net
    environment:
      REPO: contreras-adr/devops-training-2025-java-app
      TOKEN: A6CZQVUU6XKCN2YQSSGYRZLH624KM
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1


  # runner:
  #   image: tcardonne/github-runner:latest
  #   depends_on:
  #     - dind
  #   networks:
  #     - devops_training_net
  #   environment:
  #     RUNNER_NAME: "runner-python-app"
  #     RUNNER_REPOSITORY_URL: devops-training-2025-java-app.git
  #     RUNNER_ORGANIZATION_URL: https://github.com/contreras-adr
  #     GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
  #     RUNNER_TOKEN: A6CZQVQE4UJU2MTCWUKQIODH62OB2
  #     RUNNER_LABELS: docker
  #     DOCKER_HOST: tcp://docker:2376
  #     DOCKER_CERT_PATH: /certs/client
  #     DOCKER_TLS_VERIFY: 1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  